### ISSUE TITLE
适配Halo 2.20LTS

### ISSUE THREAD

**Issue by QingFeng-awa** [f2ccloud/theme-ocean#18]
[/halo-sigs/plugin-oauth2/ issue 登录跳转地址错误 #67](https://github.com/halo-sigs/plugin-oauth2/issues/67)
![[JohnNiang](https://github.com/JohnNiang)](https://github.com/user-attachments/assets/29dec196-2f92-4d5d-a1c5-90bfe2fe4435)

**Comment by ruibaby** [comment]
See https://github.com/f2ccloud/theme-ocean/pull/19

/close
