### ISSUE TITLE
[BUG] 主页模块一分类过多导致显示不全

### ISSUE THREAD

**Issue by himicoswilson** [f2ccloud/theme-ocean#2]
**建议增加仅显示选中的分类**
<img width="995" alt="CleanShot 2023-04-07 at 19 21 40@2x" src="https://user-images.githubusercontent.com/92566148/230600809-db65e17a-b137-4fce-b093-6700b1d60bae.png">

**Comment by lan-yonghui** [comment]
好的，你提的方案更加实用些，晚点我会调整发布

**Comment by lan-yonghui** [comment]
菜单目前暂不支持选择具体的子菜单，目前修复了此问题，可以选择显示几个，后续可以拿到具体的菜单项会增加选中菜单功能
