### ISSUE TITLE
主题从1.1.2升级到1.2.1后，点击文章报错

### ISSUE THREAD

**Issue by zwz9599** [f2ccloud/theme-ocean#3]
halo版本2.5.2，由于1.1.2版本主题分页存在问题，升级主题至1.2.1，点击文章报错
![image](https://github.com/f2ccloud/theme-ocean/assets/71952443/e5b92c5b-07cf-44df-b52d-ba9e60fb386e)
后端日志
![image](https://github.com/f2ccloud/theme-ocean/assets/71952443/fad61e17-36db-4048-87d6-c3c0da7f7a57)
![image](https://github.com/f2ccloud/theme-ocean/assets/71952443/b116e233-9ae4-4ad4-9bb9-ba7ef0e9582f)
![image](https://github.com/f2ccloud/theme-ocean/assets/71952443/35c56f23-2a94-44d1-b2d7-8a40fbbdcb67)
回退1.1.2就不报错了，但分页无法使用

**Comment by ghost** [comment]
全新安装一下看看呢，或者提供更多的信息，目前我这边没有复现这个问题

**Comment by zwz9599** [comment]
> 

卸载直接安装新版本试过了，也不行，报错还是一样的

**Comment by lan-yonghui** [comment]
需要查看下主题那边的配置项，看着是有个默认值不存在导致的
