### ISSUE TITLE
触发了tags的bug 500服务器内部错误

### ISSUE THREAD

**Issue by broommonk** [f2ccloud/theme-ocean#6]
可以在线访问：https://publish.feeflash.com/tags/chang-jian-wen-ti
我也不知道怎样触发了tags的bug 500服务器内部错误
提示 500 服务器内部错误

在halo提 issue ，回复是：
给对应的主题提 issue，这非 halo的问题，看起来是因为没有分类但是取了一个下标为0的分类导致的数组越界问题。

希望能修正。

**Comment by broommonk** [comment]
2023-09-11T21:40:36.529+08:00 ERROR 8 --- [boundedElastic-3] a.w.r.e.AbstractErrorWebExceptionHandler : [a57547a2-317]  500 Server Error for HTTP GET "/tags/chang-jian-wen-ti"

org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "post.categories[0].status.permalink" (template: "modules/post-card" - line 33, col 9)
	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler run.halo.app.theme.router.factories.TagPostRouteFactory$$Lambda$2321/0x00007f1db8ac8000@786a9d3c [DispatcherHandler]
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HaloAnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/tags/chang-jian-wen-ti" [ExceptionHandlingWebHandler]

**Comment by lan-yonghui** [comment]
1.4.2 done
