### ISSUE TITLE
ocean的主题，页面显示在哪里

### ISSUE THREAD

**Issue by fenhuahua** [f2ccloud/theme-ocean#7]
![image](https://github.com/f2ccloud/theme-ocean/assets/153573296/ccf2eca5-8910-4dda-b30a-f005b4bb8594)
这个页面，怎么在网址上显示，怎么设置才能出现，没看见效果。

**Comment by lan-yonghui** [comment]
这个是单独的页面，页面配置好后，给对应的菜单中增加即可显示！可以看下官方文档: https://docs.halo.run/
