### ISSUE TITLE
请问这个图表和下面的标题在哪里设置的

### ISSUE THREAD

**Issue by CherishSmile** [f2ccloud/theme-ocean#8]
<img width="298" alt="image" src="https://github.com/f2ccloud/theme-ocean/assets/17586122/facca2ca-3088-4b17-a122-6ff3f5b5bab2">

**Comment by lan-yonghui** [comment]
这个是主题 + 菜单配置的，icon在菜单中配置！
![image](https://github.com/f2ccloud/theme-ocean/assets/81747598/8d502efc-e790-457f-b3e4-de9dfc274187)
