### ISSUE TITLE
优化文章查看页面内容样式

### ISSUE THREAD

**Issue by liuboF2c** [f2ccloud/theme-ocean#9]
如图，同样的文章，使用知识库发布时内容之间没有间隔，紧贴在一起，使用默认主题的展示样式则有合理的间隔。期望能跟Halo默认主题一样展示内容。
知识库主题：
![image](https://github.com/f2ccloud/theme-ocean/assets/30886198/5692dcc2-17ce-4096-8ba8-ab474e706d39)

默认主题：
![image](https://github.com/f2ccloud/theme-ocean/assets/30886198/a2c4a8d5-43f8-40a8-bdfd-3a0d0ac82805)

**Comment by lan-yonghui** [comment]
这个 ui 定型的！！暂时不会修改
